using System;

// Class that acts as a data structure for storing information about an individual message in a conversation
[Serializable]
public class Message
{
    // The message text
    public string text;
    // True = message was generated by user, false = message was generated by chatbot
    public bool userWasSpeaker;
    // The date and time that the message was created
    public string timeProcessed;
}
